image: 
  file: .gitpod.Dockerfile

tasks:
  - name: Set .NET Environment Variables
    before: | 
      gp env DOTNET_ENVIRONMENT=Development 
      gp env DOTNET_URLS=http://localhost:5000
      gp env DOTNET_NOLOGO=1
      gp env NUGET_PACKAGES="/workspace/.nuget/packages" # redirect the nuget package cache into the workspace directory, so it gets cached by gitpod prebuilds
      eval $(gp env -e)
  - name: Build Project
    init: | 
      eval $(gp env -e)
      dotnet build ./src/Helpo/Helpo.csproj
  - name: Pull RavenDB Docker Container
    init: docker pull ravendb/ravendb
  - name: Run RavenDB Docker Container
    command: docker run --rm -d -p 8080:8080 -p 38888:38888 --name RavenDB -e RAVEN_Setup_Mode=None -e RAVEN_License_Eula_Accepted=true -e RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork ravendb/ravendb

ports:
  - port: 5000
    onOpen: notify
    visibility: private
  - port: 8080
    onOpen: notify
    visibility: private

gitConfig:
  pull.rebase: "true"
  format.pretty: "oneline"
  fetch.prune: "true"
  alias.b: "!git checkout -b"
  alias.s: "!git status"
  alias.m: "!git checkout main"
  alias.mp: "!git checkout main; git pull;"
  alias.branchname: "!git rev-parse --abbrev-ref HEAD"
  alias.pub: "!git push -u origin $(git branchname)"
  alias.ca: "!git add -A; git commit -m"
  alias.fix: "!git add -A; git commit --amend --no-edit"
  alias.rebaseonm: "!git rebase --onto main main $(git branchname)"
  alias.mbranches: "!git branch -vv | grep ': gone]' | awk '{print $1}'"
  alias.delmbranches: "!git branch -vv | grep ': gone]' | awk '{print $1}' | xargs git branch -D"

vscode:
  extensions:
    - muhammad-sammy.csharp
    - jsw.csharpextensions
    - pkief.material-icon-theme
